# frozen_string_literal: true

ruby '3.3.8'

source 'https://rubygems.org'

gem 'bcrypt'
gem 'dry-validation'
gem 'foreman'
gem 'json'
gem 'pg'
gem 'pony'
gem 'puma', '~> 6.0'
gem 'rack-accept'
gem 'rack-cors', require: 'rack/cors'
gem 'rake'
gem 'rom'
gem 'rom-sql'
gem 'sinatra'
gem 'swagger-ui_rails', '~> 2.0'

group :development, :test do
  gem 'database_cleaner'
  gem 'pry'
  gem 'pry-remote'
  gem 'rack-test'
  gem 'rerun'
  gem 'rom-factory'
  gem 'rspec'
  gem 'rubocop'
  gem 'rubocop-rake', '~> 0.5.1'
  gem 'rubocop-rspec', '~> 2.1'
  gem 'ruby-lint'
  gem 'shotgun'
end

gem 'dry-validation-matchers', '~> 1.2'
