<?php if ($this->checkGiftCards()):?>
    <button id="square_giftcards_refund" title="Refund Offline" type="button" class="action-default scalable save submit-button primary">
        <span>Refund Gift Cards</span>
    </button>

    <script>
        require([
            'jquery'
        ], function ($) {
            $("#square_giftcards_refund").click(function () {
                var giftCards = document.getElementsByClassName('square-giftcard');
                var data = [];

                for (var i = 0; i < giftCards.length; i++) {
                    if (giftCards[i].value) {
                        data.push({amount: giftCards[i].value, entity_id: giftCards[i].getAttribute("giftcard-id")});
                    }
                }

                if (data.length > 0) {
                    var giftCardsData = JSON.stringify(data);

                    $.ajax({
                        url: '<?php echo $this->getRequiredUrl() ?>',
                        data: {
                            giftCards: giftCardsData,
                            order_id: <?php echo $this->getRequest()->getParam('order_id'); ?>,
                            invoice_id: <?php echo $this->getRequest()->getParam('invoice_id'); ?>,
                        },
                        type: "POST",
                        success: function (response) {
                            window.location.href = response;
                        },
                        fail: function (response) {
                            console.log(response);
                            alert('Either the refund exceeded the order subtotal or the amount refunded on a gift card exceeded its original value');
                        },
                        error: function (response) {
                            console.log(response);
                            alert('Either the refund exceeded the order subtotal or the amount refunded on a gift card exceeded its original value');
                        }
                    });
                }

                data = [];
            });
        });
    </script>
<?php endif; ?>
