<?php

/**
 * @var $block \Squareup\Omni\Block\Adminhtml\System\Config\Button\Message
 */

?>

<h4>In order to use this payment solution you need to go to the
    <a href="<?php echo $this->escapeUrl(
        $block->getUrl("adminhtml/system_config/edit/section/squareup_omni/")
    ); ?>">Square configuration screen</a> and configure your account in order to be able to process transactions
        using Square.
</h4>
