<script type="text/javascript">
    //<![CDATA[
    function openConnection() {
        var squareAppKey = $('squareup_omni_general_application_id');
        var squareAppSecret = $('squareup_omni_general_application_secret');
        if (squareAppKey.value.length === 0 || squareAppSecret.value.length === 0){
            alert('Please fill in the Square Application Id and Square Application Secret');
            return false;
        }

        var squareUrl = '<?php echo $this->buildOauthUrl(); ?>' + squareAppKey.value;
        console.log(squareUrl);
        window.open(squareUrl, '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');
    }
    //]]>
</script>
<?php echo $this->getButtonHtml(); ?>
