<?php

/**
 * @var \Magento\Framework\View\TemplateEngine\Php $this
 * @var \Squareup\Omni\Block\Adminhtml\Catalog\Product\Form\Inventory $block
 */

$inventories = $block->getInventory();
$locationArr = $block->getLocations();

$productId = $block->getRequest()->getParam('id');

if(!$productId){
    $parentIds = $block->getParentIds($productId);
    if(!empty($parentIds)){

        $childProductId = $productId;
        $productId = $parentIds[0];
    }
}
?>
<?php if ($this->checkEditForm()): ?>
    <table cellspacing="0" class="data data-grid data-grid-draggable">
        <thead>
        <tr class="headings">
            <th class="data-grid-th _sortable _draggable"><?php echo __('Location Name'); ?></th>
            <th class="data-grid-th _sortable _draggable"><?php echo __('Status'); ?></th>
            <th class="data-grid-th _sortable _draggable"><?php echo __('Quantity'); ?></th>
            <th class="data-grid-th _sortable _draggable"><?php echo __('Calculated At'); ?></th>
            <th class="data-grid-th _sortable _draggable"><?php echo __('Received At'); ?></th>
            <?php if ($this->helper('Squareup\Omni\Helper\Config')->getSor()): ?>
                <th class="data-grid-th _sortable _draggable"><?php echo __('Actions'); ?></th>
            <?php endif; ?>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($inventories as $inventory): ?>
            <tr>
                <td class="location-name" data-location="<?php echo $inventory->getLocationId(); ?>"><?php echo $locationArr[$inventory->getLocationId()]; ?></td>
                <td><?php echo $inventory->getStatus(); ?></td>
                <?php if ($this->helper('Squareup\Omni\Helper\Config')->getSor()): ?>
                    <td><input type="text" class="squareup-quantity" name="quantity" value="<?php echo $inventory->getQuantity(); ?>" /></td>
                <?php else: ?>
                    <td><?php echo $inventory->getQuantity(); ?></td>
                <?php endif; ?>
                <td><?php echo $inventory->getCalculatedAt(); ?></td>
                <td><?php echo $inventory->getReceivedAt(); ?></td>
                <?php if ($this->helper('Squareup\Omni\Helper\Config')->getSor()): ?>
                    <td>
                        <button type="button" class="update-quantity"><?php echo __('Update qty'); ?></button>
                        <button type="button" class="remove"><?php echo __('Remove'); ?></button>
                    </td>
                <?php endif; ?>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>

    <?php if ($this->helper('Squareup\Omni\Helper\Config')->getSor()): ?>
        <div id="add-location">
            <button type="button" class="add-location">Add location</button>
        </div>
    <?php endif; ?>


    <div id="popup-modal">
        <div class="modal-content">
            <?php if(count($block->getNewLocations())): ?>
                <form id="my-custom-form" action="<?php echo $this->getUrl('square/inventory/location'); ?>" method="post">
                    <div><input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" /></div>
                    <div><input name="product_id" type="hidden" value="<?php echo $block->getRequest()->getParam('id'); ?>" /></div>
                    <table class="modal-inputs">
                        <tr>
                            <td>Location name</td>
                            <td>
                                <select name="location">
                                    <?php foreach ($this->getNewLocations() as $location): ?>
                                        <option value="<?php echo $location->getSquareId();?>">
                                            <?php echo $location->getName() ;?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </td>
                        </tr>
                        <tr>
                            <td>Quantity</td>
                            <td>
                                <input type="text" id="new-location-qty" name="qty" />
                                <span id="qty-alert-message"></span>
                            </td>
                        </tr>
                    </table>
                    <div class="save-location">
                        <button type="button" class="save-location-button">Save</button>
                    </div>
                </form>
            <?php else: ?>
                <div class="no-locations">
                    <span><?php echo 'No new locations available';?></span>
                </div>
            <?php endif; ?>
        </div>
    </div>

    <script>
    	<?php
            if(isset($childProductId)){
                echo 'var childProductId = ' . $childProductId . ';';
            }
        ?>
        var baseUrl = "<?php echo $block->getUrl('square/inventory/update'); ?>";

        require(
            [
                'jquery',
                'Magento_Ui/js/modal/modal',
                'Magento_Ui/js/modal/confirm',
                'Magento_Ui/js/modal/alert',
                'mage/translate'
            ],
            function($, modal, confirm, alert) {
                $(document).ready(function () {
                    var options = {
                        type: 'popup',
                        responsive: true,
                        innerScroll: true,
                        modalClass: 'rebates-popup'
                    };

                    var popup = modal(options, $('#popup-modal'));

                    var buttons = $(".update-quantity");
                    var removeButtons = $(".remove");
                    var trigger = $(".add-location");
                    var saveButton = $(".save-location-button");
                    var qtyInput = $("#new-location-qty");
                    var qtyInputAlert = $("#qty-alert-message");

                    buttons.each(function (index, button) {
                        $(button).click(callAjax);
                    });

                    removeButtons.each(function (index, button) {
                        $(button).click(callAjaxRemove);
                    });

                    trigger.click(function () {
                        $('#popup-modal').modal('openModal');
                    });

                    if (saveButton) {
                        saveButton.click(function () {
                            if (qtyInput.val().length === 0) {
                                qtyInputAlert.html("Please enter a quantity value");
                                return null;
                            }

                            if (isNaN(parseInt(qtyInput.val())) || parseInt(qtyInput.val()) === 0) {
                                qtyInputAlert.html("Quantity must be a number greater than 0");
                                return null;
                            }

                            $("#my-custom-form").submit();
                        });
                    }
                });

                function callAjax(event)
                {
                    var productId = <?php echo $productId; ?>;
                    var form = new FormData();
                    var quantity = event.target.closest("tr").getElementsByClassName("squareup-quantity")[0].value;
                    var location = event.target.closest("tr").getElementsByClassName("location-name")[0];
                    var location_id = location.getAttribute('data-location');
                    var locationId = "<?php echo $this->helper('Squareup\Omni\Helper\Config')->getLocationId(); ?>";

                    form.append("quantity", quantity);
                    form.append("location_id", location_id);
                    form.append("productId", productId);
                    form.append("form_key", window.FORM_KEY);

                    var xhr = new XMLHttpRequest();
                    xhr.open("POST", baseUrl, true);
                    xhr.setRequestHeader("cache-control", "no-cache");
                    xhr.onload = function () {
                        if (200 === xhr.status) {
                            if (location_id == locationId) {
                                debugger;
                                // update main quantity input
                                $('input[name="product[quantity_and_stock_status][qty]"]').val(quantity);
                                // document.getElementById("inventory_qty").setAttribute('value', quantity);
                                // document.getElementById("original_inventory_qty").setAttribute('value', quantity);
                                // document.getElementById("inventory_qty").value = quantity;
                            }
                            alert({
                                content: ("Inventory was updated."),
                            });
                        } else if (400 === xhr.status) {
                            alert({
                                content: ("Product is not associated with any website. Product update failed."),
                            });
                        }
                    };
                    xhr.send(form);
                }

                function callAjaxRemove(event) {

                    confirm({
                        content: "<?= /* @escapeNotVerified */ __('Are you sure you want to remove the product from that location?') ?>",
                        actions: {
                            confirm: function () {

                                var removeSquareLocationUrl = "<?php echo $block->getUrl('square/inventory/removeSquareInventory', array('_secure' => true)); ?>";
                                var location = $(event.target).closest("tr").find(".location-name");
                                var productId = <?php echo $productId; ?>;
                                var location_id = location.data('location');

                                var data = {
                                    locationId: location_id,
                                    productId: productId,
                                    form_key: window.FORM_KEY,
                                    isAjax: true
                                };

                                if (typeof(childProductId) !== "undefined") {
                                    data["childProductId"] = childProductId;
                                }

                                $.ajax({
                                    url: removeSquareLocationUrl,
                                    type: 'post',
                                    data: data,
                                    dataType: 'json',
                                    success: function (data, textStatus, jqXHR) {

                                        var location = $(event.target).closest("tr");
                                        location.remove();
                                        alert({
                                            title: $.mage.__("Success"),
                                            content: $.mage.__("Location was removed."),
                                            always: function(){
                                                window.location.reload();
                                            }
                                        });
                                    },
                                    error: function (jqXHR, textStatus, error) {
                                        alert({
                                            content: ("Cannot remove square inventory record."),
                                            always: function(){
                                                window.location.reload();
                                            }
                                        });
                                    },
                                });
                            }
                        }
                    });
                }
            }
        );
    </script>
<?php endif; ?>
