<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\View */ ?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()) : return '';endif; ?>
<?php
    $transactionId = $order->getSquareOrderId();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $transactionModel = $objectManager->create('\Squareup\Omni\Model\ResourceModel\Transactions');
    $note = $transactionModel->loadNoteBySquareId($transactionId);
    $pos = ($note == 'Transaction from REGISTER')? true : false;
?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <?php if(true === $pos): ?>
            <span class="title"><?= /* @escapeNotVerified */ __('Square POS') ?></span>
        <?php else: ?>
            <span class="title"><?= /* @escapeNotVerified */ __('Shipping &amp; Handling Information') ?></span>
        <?php endif; ?>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()) : ?>
            <p><a href="#" id="linkId" onclick="popWin('<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($order) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')" title="<?= /* @escapeNotVerified */ __('Track Order') ?>"><?= /* @escapeNotVerified */ __('Track Order') ?></a></p>
        <?php endif; ?>
        <?php if ($order->getShippingDescription()): ?>
            <?php if(true === $pos): ?>
                <strong><?= /* @escapeNotVerified */ __('Square POS: custom amounts, taxes, shipping, and other costs') ?>:</strong>
            <?php else: ?>
                <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>
            <?php endif; ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()): ?>
                <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
            <?php else: ?>
                <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
            <?php endif; ?>
            <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

            <?= /* @escapeNotVerified */ $_excl ?>
            <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl): ?>
                (<?= /* @escapeNotVerified */ __('Incl. Tax') ?> <?= /* @escapeNotVerified */ $_incl ?>)
            <?php endif; ?>
        <?php else: ?>
            <?= /* @escapeNotVerified */ __('No shipping information available') ?>
        <?php endif; ?>
    </div>
</div>
